name: 'compress-action'
description: 'Brotli compress all .js .html and .css files in a directory recursively'
author: 'charlesworth'
branding:
  icon: 'minimize-2'
  color: 'green'
inputs:
  target-directory:
    description: 'directory to target'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target-directory }}
